src/Form/AttachmentType.php
<?php

namespace Hgabka\EmailBundle\Form;

use Hgabka\EmailBundle\Entity\Attachment;
use Hgabka\MediaBundle\Admin\MediaAdmin;
use Hgabka\MediaBundle\Form\Type\MediaSimpleType;
use Hgabka\MediaBundle\Form\Type\MediaType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class AttachmentType extends AbstractType
{
    /** @var MediaAdmin */
    protected $mediaAdmin;

    /**
     * AttachmentType constructor.
     */
    public function __construct(MediaAdmin $mediaAdmin)
    {
        $this->mediaAdmin = $mediaAdmin;
    }

    /**
     * Builds the form.
     *
     * This method is called for each type in the hierarchy starting form the
     * top most type. Type extensions can further modify the form.
     *
     * @see FormTypeExtensionInterface::buildForm()
     *
     * @param FormBuilderInterface $builder The form builder
     * @param array                $options The options
     */
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $mediaAccess = $this->mediaAdmin->hasAccess('list');
        if ($mediaAccess) {
            $builder
                ->add('media', MediaType::class, ['label' => false, 'required' => false, 'mediatype' => 'file', 'foldername' => 'attachment']);
        } else {
            $builder
                ->add('media', MediaSimpleType::class, [
                    'required' => false,
                    'label' => false,
                    'foldername' => 'attachment',
                    'parentfolder' => 'fileroot',
                    ]);
        }
    }

    /**
     * Sets the default options for this type.
     *
     * @param OptionsResolver $resolver the resolver for the options
     */
    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Attachment::class,
        ]);
    }

    /**
     * Returns the name of this type.
     *
     * @return string The name of this type
     */
    public function getBlockPrefix(): string
    {
        return 'hg_email_attachment_type';
    }
}

src/Form/EmailTemplateRecipientsType.php
<?php

namespace Hgabka\EmailBundle\Form;

use Hgabka\EmailBundle\Helper\RecipientManager;
use Hgabka\EmailBundle\Helper\TemplateTypeManager;
use Hgabka\EmailBundle\Model\EmailTemplateRecipientTypeInterface;
use Hgabka\EmailBundle\Recipient\DefaultEmailTemplateRecipientType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormEvent;
use Symfony\Component\Form\FormEvents;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\Form\FormView;
use Symfony\Component\OptionsResolver\OptionsResolver;

class EmailTemplateRecipientsType extends AbstractType
{
    /**
     * RecipientsType constructor.
     */
    public function __construct(protected readonly RecipientManager $manager, protected readonly TemplateTypeManager $templateTypeManager)
    {
    }

    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->addEventListener(FormEvents::PRE_SET_DATA, function (FormEvent $event) use ($options) {
                $data = $event->getData();
                $form = $event->getForm();

                if (!empty($data)) {
                    foreach ($form->all() as $name => $field) {
                        $form->remove($name);
                    }
                }

                if (0 === \count($form)) {
                    $templateType = $this->templateTypeManager->getTemplateType($options['template_type']);

                    if ($templateType) {
                        if (empty($data)) {
                            if (RecipientManager::RECIPIENT_TYPE_TO === $options['recipients_type'] && !empty($templateType->getDefaultRecipients())) {
                                $recipients = $templateType->getDefaultRecipients();
                                if (\array_key_exists('type', $recipients)) {
                                    $recipients = [$recipients];
                                }

                                foreach ($recipients as $recTypeData) {
                                    if (!empty($recTypeData['type'])) {
                                        $this->addRecipientType(null, $form, $recTypeData['type'], $recTypeData['params'] ?? null, false, $recTypeData['label'] ?? null);
                                    }
                                }
                            } elseif (RecipientManager::RECIPIENT_TYPE_CC === $options['recipients_type'] && !empty($templateType->getDefaultCc())) {
                                $recipients = $templateType->getDefaultCc();
                                if (\array_key_exists('type', $recipients)) {
                                    $recipients = [$recipients];
                                }

                                foreach ($recipients as $recTypeData) {
                                    if (!empty($recTypeData['type'])) {
                                        $this->addRecipientType(null, $form, $recTypeData['type'], $recTypeData['params'] ?? null, false, $recTypeData['label'] ?? null);
                                    }
                                }
                            } elseif (RecipientManager::RECIPIENT_TYPE_BCC === $options['recipients_type'] && !empty($templateType->getDefaultBcc())) {
                                $recipients = $templateType->getDefaultBcc();
                                if (\array_key_exists('type', $recipients)) {
                                    $recipients = [$recipients];
                                }

                                foreach ($recipients as $recTypeData) {
                                    if (!empty($recTypeData['type'])) {
                                        $this->addRecipientType(null, $form, $recTypeData['type'], $recTypeData['params'] ?? null, false, $recTypeData['label'] ?? null);
                                    }
                                }
                            } else {
                                if (RecipientManager::RECIPIENT_TYPE_TO === $options['recipients_type']) {
                                    $this->addRecipientType(null, $form, DefaultEmailTemplateRecipientType::class);
                                }
                            }
                        } else {
                            $removable = (RecipientManager::RECIPIENT_TYPE_TO === $options['recipients_type'] && empty($templateType->getDefaultRecipients())) ||
                                (RecipientManager::RECIPIENT_TYPE_CC === $options['recipients_type'] && empty($templateType->getDefaultCc())) ||
                                (RecipientManager::RECIPIENT_TYPE_BCC === $options['recipients_type'] && empty($templateType->getDefaultBcc()));

                            foreach ($data as $name => $typeData) {
                                $label = null;
                                if (RecipientManager::RECIPIENT_TYPE_TO === $options['recipients_type']) {
                                    $defs = $templateType->getDefaultRecipients();
                                } elseif (RecipientManager::RECIPIENT_TYPE_CC === $options['recipients_type']) {
                                    $defs = $templateType->getDefaultCc();
                                } elseif (RecipientManager::RECIPIENT_TYPE_BCC === $options['recipients_type']) {
                                    $defs = $templateType->getDefaultBcc();
                                }

                                if (!empty($defs)) {
                                    if ($defs['type'] === $typeData['type'] && !empty($defs['label'])) {
                                        $label = $defs['label'];
                                    }
                                }

                                $this->addRecipientType($name, $form, $typeData['type'], $typeData, $removable, $label);
                            }
                        }
                    }
                }
            })
            ->addEventListener(FormEvents::PRE_SUBMIT, function (FormEvent $event) use ($options) {
                $data = $event->getData();
                $form = $event->getForm();
                foreach ($form->all() as $name => $field) {
                    $form->remove($name);
                }

                $templateType = $this->templateTypeManager->getTemplateType($options['template_type']);

                $removable = (RecipientManager::RECIPIENT_TYPE_TO === $options['recipients_type'] && empty($templateType->getDefaultRecipients())) ||
                    (RecipientManager::RECIPIENT_TYPE_CC === $options['recipients_type'] && empty($templateType->getDefaultCc())) ||
                    (RecipientManager::RECIPIENT_TYPE_BCC === $options['recipients_type'] && empty($templateType->getDefaultBcc()));

                if (0 === \count($form) && !empty($data)) {
                    foreach ($data as $name => $typeData) {
                        $this->addRecipientType($name, $form, $typeData['type'] ?? null, $typeData, $removable);
                    }

                    $form->setData($data);
                } elseif (RecipientManager::RECIPIENT_TYPE_TO !== $options['recipients_type'] && $removable && empty($data)) {
                    $form->setData($data);
                }
            })
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver
            ->setDefaults([
                'recipients_type' => RecipientManager::RECIPIENT_TYPE_TO,
                'template_type' => null,
                'admin' => null,
            ])
        ;
    }

    public function buildView(FormView $view, FormInterface $form, array $options): void
    {
        $view->vars['admin'] = $options['admin'];
        $view->vars['recipientsType'] = $options['recipients_type'];
        $tplType = $this->templateTypeManager->getTemplateType($options['template_type']);
        $view->vars['add_button'] =
            (RecipientManager::RECIPIENT_TYPE_TO === $options['recipients_type'] && (!$tplType || empty($tplType->getDefaultRecipients()))) ||
            (RecipientManager::RECIPIENT_TYPE_CC === $options['recipients_type'] && (!$tplType || empty($tplType->getDefaultCc()))) ||
            (RecipientManager::RECIPIENT_TYPE_BCC === $options['recipients_type'] && (!$tplType || empty($tplType->getDefaultBcc())))
        ;
        $view->vars['dataType'] = 'template';
    }

    public function getBlockPrefix(): string
    {
        return 'template_recipients';
    }

    protected function addRecipientType($name, FormInterface $form, $type, $params = null, $removable = true, $label = null): void
    {
        /** @var EmailTemplateRecipientTypeInterface $recType */
        $recType = $this->manager->getTemplateRecipientType($type);
        if (!$recType) {
            return;
        }
        if (null !== $params) {
            $recType->setParams($params);
        }

        $builder = $this->manager->createTemplateRecipientTypeFormBuilder($name ?? uniqid('rectype_'), $type, $removable, $label);
        if ($builder) {
            $form
                ->add($builder->getForm())
            ;
        }
    }
}

src/Form/MessageMailType.php
<?php

namespace Hgabka\EmailBundle\Form;

use Hgabka\UtilsBundle\Form\Type\LocaleType;
use Hgabka\UtilsBundle\Helper\HgabkaUtils;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Validator\Constraints\Email;
use Symfony\Component\Validator\Constraints\NotBlank;

class MessageMailType extends AbstractType
{
    /** @var HgabkaUtils */
    protected $hgabkaUtils;

    /**
     * MessageMailType constructor.
     */
    public function __construct(HgabkaUtils $hgabkaUtils)
    {
        $this->hgabkaUtils = $hgabkaUtils;
    }

    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder->add('email', EmailType::class, [
            'label' => 'hg_email.label.email',
            'required' => true,
            'constraints' => [
                new Email(),
                new NotBlank(),
            ],
        ])
        ;
        if (\count($this->hgabkaUtils->getAvailableLocales()) > 1) {
            $builder
                ->add('locale', LocaleType::class, [
                    'label' => 'hg_email.label.locale',
                ])
            ;
        }
    }

    /**
     * Returns the name of this type.
     *
     * @return string The name of this type
     */
    public function getBlockPrefix(): string
    {
        return 'hg_email_message_mail_type';
    }
}

src/Form/MessageSendType.php
<?php

namespace Hgabka\EmailBundle\Form;

use Hgabka\EmailBundle\Entity\Message;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class MessageSendType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder->add('sendTime', SendType::class, [
            'label' => false,
        ]);
    }

    /**
     * Sets the default options for this type.
     *
     * @param OptionsResolver $resolver the resolver for the options
     */
    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Message::class,
        ]);
    }

    /**
     * Returns the name of this type.
     *
     * @return string The name of this type
     */
    public function getBlockPrefix(): string
    {
        return 'hg_email_message_send_type';
    }
}

src/Form/SendType.php
<?php

namespace Hgabka\EmailBundle\Form;

use Sonata\Form\Type\DatePickerType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\Callback;
use Symfony\Component\Validator\Constraints\Range;
use Symfony\Component\Validator\Context\ExecutionContextInterface;

class SendType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('type', ChoiceType::class, [
                'label' => 'hg_email.label.send_at',
                'choices' => [
                    'hg_email.label.send_now' => 'now',
                    'hg_email.label.send_later' => 'later',
                ],
            ])
            ->add('time', DatePickerType::class, [
                'label' => 'hg_email.label.send_time',
                'constraints' => [
                    new Range(['min' => 'now', 'minMessage' => 'hg_email.messages.send_at_error']),
                ],
                'required' => false,
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'compound' => true,
            'constraints' => [
                new Callback([
                    'callback' => function ($data, ExecutionContextInterface $context) {
                        if ('later' === $data['type'] && empty($data['time'])) {
                            $context->buildViolation('hg_email.messages.send_time_required')
                                     ->atPath('[time]')
                                     ->addViolation();
                        }
                    },
                ]),
            ],
        ]);
    }
}

src/Form/Type/MessageRecipientFormType.php
<?php

namespace Hgabka\EmailBundle\Form\Type;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FormType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormEvent;
use Symfony\Component\Form\FormEvents;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\Form\FormView;
use Symfony\Component\OptionsResolver\OptionsResolver;

class MessageRecipientFormType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        if ($options['recipient_type']) {
            $builder->add('type', HiddenType::class);
            $builder->get('type')
                    ->addEventListener(FormEvents::PRE_SET_DATA, function (FormEvent $event) use ($options) {
                        $event->setData(\get_class($options['recipient_type']));
                    })
            ;
        }
    }

    public function getParent(): ?string
    {
        return FormType::class;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver
            ->setDefaults([
                'data_class' => null,
                'recipient_type' => null,
                'auto_initialize' => false,
            ])
        ;
    }

    public function buildView(FormView $view, FormInterface $form, array $options): void
    {
        $view->vars['removable'] = true;
        $view->vars['typeName'] = $options['recipient_type'] ? $options['recipient_type']->getName() : '';
        $view->vars['blockTitle'] = $options['recipient_type'] ? $options['recipient_type']->getTitle() : '';
        $view->vars['recipientType'] = $options['recipient_type'];
    }
}

src/Resources/views/Form/fields.html.twig
{% block template_recipients_widget %}
    <div id="accordion_{{ form.vars.id }}" class="panel-group">
        {% for key,child in form %}
            {% set recipientType = child.vars.recipientType %}
            {% if recipientType.formTemplate is defined and recipientType.formTemplate is not empty %}
                {% set template = recipientType.formTemplate %}
            {% else %}
                {% set template = '@HgabkaEmail/Admin/recipient_type_form.html.twig' %}
            {% endif %}

            {% include template %}
        {% endfor %}
    </div>
    <div class="no-recipient no-recipient_{{ form.vars.id }}">
        <p>{{ 'hg_email.title.no_recipient'|trans }}</p>
    </div>
    {% if form.vars.add_button %}
        <div class="add-recipient add-recipient_{{ form.vars.id }}">
            <a href="#" class="btn btn-link recipient-add">
                <i class="fa fa-plus-circle" aria-hidden="true"></i>
                {{ 'hg_email.recipient_type.add'|trans }}
            </a>
            <div class="recipient-selector">
                <div class="form-group">
                    <label class="control-label" for="recipient_type">
                        {{ 'hg_email.label.choose_recipient_type'|trans }}
                    </label>
                    {% if form.vars.dataType == 'message' %}
                        {{ render_message_recipient_selector(form.vars.id) }}
                    {% else %}
                        {{ render_template_recipient_selector(form.vars.id) }}
                    {% endif %}
                </div>
                <div class="form-group">
                    <a href="#" id="add_recipient_submit_{{ form.vars.id }}" class="btn btn-success">
                        <i class="fa fa-plus" aria-hidden="true"></i>
                        {{ 'hg_email.label.add_recipient'|trans }}
                    </a>
                </div>
            </div>
        </div>
    {% endif %}
    <script>
        $(function () {
            var $accordion = $('#accordion_{{ form.vars.id }}');
            var $panel = $('#accordion_{{ form.vars.id }} .panel');
            var $noRecipient = $('.no-recipient_{{ form.vars.id }}');
            var $addRecipient = $('.add-recipient_{{ form.vars.id }}');
            var $selector = $('.add-recipient_{{ form.vars.id }} .recipient-selector');
            var $recipientAdd = $('.add-recipient_{{ form.vars.id }} .recipient-add');
            var $rectypeSelect = $('#rectype-select_{{ form.vars.id }}');

            if ($panel.length === 0) {
                $noRecipient.show();
            } else {
                $noRecipient.hide();
            }
            $accordion.on('click', '.recipient-remove', function (e) {
                e.preventDefault();
                $(this).parents('.panel').remove();
                if ($('#accordion_{{ form.vars.id }} .panel').length === 0) {
                    $noRecipient.show();
                } else {
                    $noRecipient.hide();
                }

                if (typeof renderUsableVars !== 'undefined') {
                    renderUsableVars();
                }
            });
            {% if form.vars.add_button %}
                $addRecipient.on('click', '.recipient-add', function (e) {
                    e.preventDefault();
                    var $typeSelect = $('#rectype-select_{{ form.vars.id }}');
                    if ($typeSelect.length > 0) {
                        $typeSelect.val('').trigger('change');
                    }
                    $selector.show();
                    $recipientAdd.hide();
                });

                $('#add_recipient_submit_{{ form.vars.id }}').click(function (e) {
                    e.preventDefault();
                    if ($('#rectype-select_{{ form.vars.id }}').val().length > 0) {
                        $.getJSON('{{ form.vars.admin.generateUrl('add_recipient', {fieldType: form.vars.recipientsType}) }}',
                                  {type: $rectypeSelect.val(), name: '{{ form.parent.vars.name }}', id: '{{ form.vars.admin.subject.id }}'}, function (data) {
                                $accordion.append(data.html);
                                $selector.hide();
                                $noRecipient.hide();
                                $recipientAdd.show();
                                $rectypeSelect.val('');
                                Admin.shared_setup($accordion);
                                if (typeof renderUsableVars !== 'undefined') {
                                    renderUsableVars();
                                }
                            });
                    }
                });
            {% endif %}
        });
    </script>
{% endblock %}

{% block message_recipients_widget %}
    {{ block('template_recipients_widget') }}
{% endblock %}