src/Entity/Message.php
<?php

namespace Hgabka\EmailBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Hgabka\Doctrine\Translatable\Annotation as Hgabka;
use Hgabka\Doctrine\Translatable\TranslatableInterface;
use Hgabka\EmailBundle\Enum\MessageStatusEnum;
use Hgabka\EmailBundle\Repository\MessageRepository;
use Hgabka\UtilsBundle\Entity\TranslatableTrait;
use Hgabka\UtilsBundle\Traits\TimestampableEntity;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Table(name: 'hg_email_message')]
#[ORM\Entity(repositoryClass: MessageRepository::class)]
class Message implements TranslatableInterface
{
    use TimestampableEntity;
    use TranslatableTrait;

    #[ORM\Id]
    #[ORM\GeneratedValue(strategy: 'AUTO')]
    #[ORM\Column(type: 'integer')]
    protected ?int $id = null;

    /**
     * @Hgabka\Translations(targetEntity="Hgabka\EmailBundle\Entity\MessageTranslation")
     */
    #[Hgabka\Translations(targetEntity: MessageTranslation::class)]
    protected Collection|array|null $translations = null;

    #[ORM\OneToMany(targetEntity: MessageSendList::class, cascade: ['all'], mappedBy: 'message', orphanRemoval: true)]
    #[Assert\Valid]
    protected Collection|array|null $sendLists = null;

    #[ORM\Column(name: 'to_data', type: 'json', nullable: true)]
    protected ?array $toData = null;

    #[ORM\Column(name: 'cc_data', type: 'json', nullable: true)]
    protected ?array $ccData = null;

    #[ORM\Column(name: 'bcc_data', type: 'json', nullable: true)]
    protected ?array $bccData = null;

    #[ORM\Column(name: 'send_at', type: 'datetime', nullable: true)]
    protected ?\DateTime $sendAt = null;

    #[ORM\Column(name: 'sent_at', type: 'datetime', nullable: true)]
    protected ?\DateTime $sentAt = null;

    #[ORM\Column(name: 'status', type: 'string', length: 20)]
    protected ?string $status = MessageStatusEnum::STATUS_INIT;

    #[ORM\ManyToOne(targetEntity: EmailLayout::class, inversedBy: 'messages', cascade: ['persist'])]
    #[ORM\JoinColumn(name: 'email_layout_id', referencedColumnName: 'id', onDelete: 'SET NULL')]
    protected ?EmailLayout $layout = null;

    #[ORM\Column(name: 'sent_mail', type: 'integer')]
    protected ?int $sentMail = 0;

    #[ORM\Column(name: 'sent_success', type: 'integer')]
    protected ?int $sentSuccess = 0;

    #[ORM\Column(name: 'sent_fail', type: 'integer')]
    protected ?int $sentFail = 0;

    #[ORM\Column(name: 'is_simple', type: 'boolean')]
    protected ?bool $isSimple = false;

    #[ORM\Column(name: 'locale', type: 'string', length: 2, nullable: true)]
    protected ?string $locale = null;

    /**
     * constructor.
     */
    public function __construct()
    {
        $this->translations = new ArrayCollection();
        $this->sendLists = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function setId(?int $id)
    {
        $this->id = $id;

        return $this;
    }

    public function getLayout(): ?EmailLayout
    {
        return $this->layout;
    }

    public function setLayout(?EmailLayout $layout): self
    {
        $this->layout = $layout;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setType(?string $status)
    {
        if (!\in_array($status, MessageStatusEnum::getAvailableStatuses(), true)) {
            throw new \InvalidArgumentException('Invalid type');
        }

        $this->status = $status;

        return $this;
    }

    public function getSendAt(): ?\DateTime
    {
        return $this->sendAt;
    }

    public function setSendAt(?\DateTime $sendAt = null): self
    {
        $this->sendAt = $sendAt;

        return $this;
    }

    public function getSentMail(): ?int
    {
        return $this->sentMail;
    }

    public function setSentMail(?int $sentMail): self
    {
        $this->sentMail = $sentMail;

        return $this;
    }

    public function getSentSuccess(): ?int
    {
        return $this->sentSuccess;
    }

    public function setSentSuccess(?int $sentSuccess): self
    {
        $this->sentSuccess = $sentSuccess;

        return $this;
    }

    public function getSentFail(): ?int
    {
        return $this->sentFail;
    }

    public function setSentFail(?int $sentFail): self
    {
        $this->sentFail = $sentFail;

        return $this;
    }

    public function getisSimple(): ?bool
    {
        return $this->isSimple;
    }

    public function setIsSimple(?bool $isSimple): self
    {
        $this->isSimple = $isSimple;

        return $this;
    }

    public function getLocale(): ?string
    {
        return $this->locale;
    }

    public function setLocale(?string $locale): self
    {
        $this->locale = $locale;

        return $this;
    }

    public function getSendLists(): Collection|array|null
    {
        return $this->sendLists;
    }

    public function setSendLists(Collection|array|null $sendLists): self
    {
        $this->sendLists = $sendLists;

        return $this;
    }

    public function addSendList(MessageSendList $sendList): self
    {
        if (!$this->sendLists->contains($sendList)) {
            $this->sendLists[] = $sendList;

            $sendList->setMessage($this);
        }

        return $this;
    }

    public function removeSendList(MessageSendList $sendList): self
    {
        $this->sendLists->removeElement($sendList);

        return $this;
    }

    public static function getTranslationEntityClass(): string
    {
        return MessageTranslation::class;
    }

    public function getToData(): ?array
    {
        return $this->toData;
    }

    public function setToData(?array $toData): self
    {
        $this->toData = $toData;

        return $this;
    }

    public function getCcData(): ?array
    {
        return $this->ccData;
    }

    public function setCcData(?array $ccData): self
    {
        $this->ccData = $ccData;

        return $this;
    }

    public function getBccData(): ?array
    {
        return $this->bccData;
    }

    public function setBccData(?array $bccData)
    {
        $this->bccData = $bccData;

        return $this;
    }

    public function getSentAt(): ?\DateTime
    {
        return $this->sentAt;
    }

    public function setSentAt(?\DateTime $sentAt): self
    {
        $this->sentAt = $sentAt;

        return $this;
    }

    public function isPrepareable(): bool
    {
        return MessageStatusEnum::STATUS_INIT === $this->getStatus() || null === $this->getId();
    }

    public function isUnprepareable(): bool
    {
        return \in_array($this->getStatus(), [MessageStatusEnum::STATUS_KULDENDO, MessageStatusEnum::STATUS_FOLYAMATBAN], true);
    }

    public function isBeingSent(): bool
    {
        return \in_array($this->getStatus(), [MessageStatusEnum::STATUS_ELKULDVE, MessageStatusEnum::STATUS_FOLYAMATBAN], true);
    }

    public function isPrepared(): bool
    {
        return MessageStatusEnum::STATUS_KULDENDO === $this->getStatus();
    }

    public function getSendTime(): array
    {
        if (null === $this->sendAt) {
            return [
                'type' => 'now',
                'time' => null,
            ];
        }

        return [
                'type' => 'later',
                'time' => $this->sendAt,
            ];
    }

    public function setSendTime(?array $data): self
    {
        if (!isset($data['type']) || 'now' === $data['type']) {
            $this->setSendAt(null);
        } else {
            $this->setSendAt($data['time']);
        }

        return $this;
    }

    public function getSubject(?string $locale = null): ?string
    {
        return $this->translate($locale)->getSubject();
    }

    public function setStatus(?string $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getStatusDisplay(): string
    {
        $choices = MessageStatusEnum::getStatusTextChoices();

        return $choices[$this->getStatus()] ?? '';
    }

    public function getName(?string $locale = null): ?string
    {
        return $this->translate($locale)->getName();
    }

    public function getFromName(?string $locale = null): ?string
    {
        return $this->translate($locale)->getFromName();
    }

    public function getFromEmail(?string $locale = null): ?string
    {
        return $this->translate($locale)->getFromEmail();
    }
}

src/Controller/MessageController.php
<?php

namespace Hgabka\EmailBundle\Controller;

use Doctrine\Persistence\ManagerRegistry;
use Hgabka\EmailBundle\Entity\MessageList;
use Hgabka\EmailBundle\Entity\MessageListSubscription;
use Hgabka\EmailBundle\Entity\MessageQueue;
use Hgabka\EmailBundle\Entity\MessageSubscriber;
use Hgabka\EmailBundle\Helper\MailBuilder;
use Hgabka\EmailBundle\Helper\RecipientManager;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Mime\Address;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\Routing\RouterInterface;

class MessageController extends AbstractController
{
    /**
     * The webversion action.
     *
     * @param mixed $id
     * @param mixed $hash
     *
     * @return Response
     */
    #[Route('/{id}/webversion/{hash}', name: 'hgabka_email_message_webversion', requirements: ['id' => '\d+'], methods: ['GET'])]
    public function webversionAction(Request $request, RouterInterface $router, MailBuilder $mailBuilder, RecipientManager $recipientManager, ManagerRegistry $doctrine, int $id, string $hash): Response
    {
        /** @var MessageQueue $queue */
        $queue = $doctrine->getRepository(MessageQueue::class)->find($id);
        if (!$queue || $queue->getHash() !== $hash) {
            throw $this->createNotFoundException('Invalid message');
        }
        $toName = $queue->getToName();
        $toEmail = $queue->getToEmail();

        $to = empty($toName) ? new Address($toEmail) : new Address($toEmail, $toName);
        $params = json_decode($queue->getParameters(), true);

        if (!isset($params['type'])) {
            return false;
        }
        $recType = $recipientManager->getMessageRecipientType($params['type']);
        if (!$recType) {
            return false;
        }
        $recType->setParams($params['typeParams'] ?? []);
        if (!isset($params['vars'])) {
            $params['vars'] = [];
        }

        ['bodyHtml' => $bodyHtml] = $mailBuilder->createMessageMail($queue->getMessage(), $to, $queue->getLocale(), true, $params, $recType, false, true, $queue);

        return new Response($bodyHtml);
    }

    /**
     * The unsubscribe action.
     *
     * @param mixed $token
     *
     * @return Response
     */
    #[Route('/unsubscribe/{token}', name: 'hgabka_email_message_unsubscribe')]
    public function unsubscribeAction(Request $request, ManagerRegistry $doctrine, string $token): Response
    {
        $em = $doctrine->getManager();

        $subscr = $em
            ->getRepository(MessageSubscriber::class)
            ->findOneByToken($token)
        ;

        if (!$subscr) {
            throw $this->createNotFoundException('Missing subscriber');
        }

        if ($request->query->has('list_id')) {
            $list = $em
                ->getRepository(MessageList::class)
                ->findOneById($request->query->get('list_id'))
            ;

            if ($list) {
                $sub = $em
                    ->getRepository(MessageListSubscription::class)
                    ->findForSubscriberAndList($subscr, $list)
                ;

                if ($sub) {
                    $em->remove($sub);
                    $em->flush();
                }
            }
        } else {
            $em->remove($subscr);
            $em->flush();
        }

        return $this->render('@HgabkaEmail/Message/unsubscribe.html.twig');
    }
}

src/Resources/views/Admin/Message/edit.html.twig
{% extends '@SonataAdmin/CRUD/base_edit.html.twig' %}
{% import '@HgabkaEmail/Admin/edit_form_macro.html.twig' as form_helper %}

{% block title %}
    {% if objectId|default(admin.id(object)) is not null %}
        {{ "title_edit"|trans({'%name%': admin.toString(object) }, 'SonataAdminBundle') }}
    {% else %}
        {{ "title_create"|trans({}, 'SonataAdminBundle') }}
    {% endif %}
{% endblock %}

{% block form %}
    {{ sonata_block_render_event('sonata.admin.edit.form.top', { 'admin': admin, 'object': object }) }}

    {# NEXT_MAJOR: remove default filter #}
    {% set url = objectId|default(admin.id(object)) is not null ? 'edit' : 'create' %}

    {% if not admin.hasRoute(url)%}
        <div>
            {{ "form_not_available"|trans({}, "SonataAdminBundle") }}
        </div>
    {% else %}
        <form
                {% if sonata_config.getOption('form_type') == 'horizontal' %}class="form-horizontal"{% endif %}
                role="form"
                {# NEXT_MAJOR: remove default filter #}
                action="{% block sonata_form_action_url %}{{ admin.generateUrl(url, {'id': objectId|default(admin.id(object)), 'uniqid': admin.uniqid, 'subclass': app.request.get('subclass')}) }}{% endblock %}"
                {% if form.vars.multipart %} enctype="multipart/form-data"{% endif %}
                method="POST"
                {% if not sonata_config.getOption('html5_validate') %}novalidate="novalidate"{% endif %}
                {% block sonata_form_attributes %}{% endblock %}
        >

            {{ include('@SonataAdmin/Helper/render_form_dismissable_errors.html.twig') }}

            {% block sonata_pre_fieldsets %}
            <div class="row">
                {% endblock %}

                {% block sonata_tab_content %}
                    {% set has_tab = ((admin.formtabs|length == 1 and admin.formtabs|keys[0] != 'default') or admin.formtabs|length > 1 ) %}

                    <div class="col-md-12">
                        {% if has_tab %}
                            {% set tab_prefix = 'tab_' ~ admin.uniqid ~ '_' ~ random() %}
                            {% set tab_query_index = app.request.query.get('_tab', 0)|split("_")|last %}
                            <div class="nav-tabs-custom">
                                <ul class="nav nav-tabs" role="tablist">
                                    {% for name, form_tab in admin.formtabs %}
                                        {% set _tab_name = tab_prefix ~ '_' ~ loop.index %}
                                        <li{% if (not app.request.query.has('_tab') and loop.index == 1) or (tab_query_index == loop.index) %} class="active"{% endif %}>
                                            <a href="#{{ _tab_name }}" class="changer-tab" aria-controls="{{ _tab_name }}" data-toggle="tab">
                                                <i class="fa fa-exclamation-circle has-errors hide" aria-hidden="true"></i> {{ form_tab.label|trans({}, form_tab.translation_domain ?: admin.translationDomain) }}
                                            </a>
                                        </li>
                                    {% endfor %}
                                </ul>
                                <div class="tab-content">
                                    {% for code, form_tab in admin.formtabs %}
                                        {% set _tab_name = tab_prefix ~ '_' ~ loop.index %}
                                        <div class="tab-pane fade{% if (not app.request.query.has('_tab') and loop.first) or (tab_query_index == loop.index) %} in active{% endif %}" id="{{ _tab_name }}">
                                            <div class="box-body  container-fluid">
                                                <div class="sonata-ba-collapsed-fields">
                                                    {% if form_tab.description != false %}
                                                        <div id="usable-vars" data-url="{{ admin.generateUrl('render_usable_vars') }}">
                                                            {{ render_message_usable_vars(object) }}
                                                        </div>
                                                    {% endif %}

                                                    {{ form_helper.render_groups(admin, form, form_tab['groups'], has_tab) }}
                                                </div>
                                            </div>
                                        </div>
                                    {% endfor %}
                                </div>
                            </div>
                        {% else %}
                            {{ form_helper.render_groups(admin, form, admin.formtabs['default'].groups, has_tab) }}
                        {% endif %}
                    </div>
                {% endblock %}

                {% block sonata_post_fieldsets %}
            </div>
            {% endblock %}

            {{ form_rest(form) }}

            {% block formactions %}
                <div class="sonata-ba-form-actions well well-small form-actions">
                    {% block sonata_form_actions %}
                        {% if app.request.isxmlhttprequest %}
                            {# NEXT_MAJOR: remove default filter #}
                            {% if objectId|default(admin.id(object)) is not null %}
                                <button type="submit" class="btn btn-success" name="btn_update"><i class="fa fa-save" aria-hidden="true"></i> {{ 'btn_update'|trans({}, 'SonataAdminBundle') }}</button>
                            {% else %}
                                <button type="submit" class="btn btn-success" name="btn_create"><i class="fa fa-plus-circle" aria-hidden="true"></i> {{ 'btn_create'|trans({}, 'SonataAdminBundle') }}</button>
                            {% endif %}
                        {% else %}
                            {% if admin.supportsPreviewMode %}
                                <button class="btn btn-info persist-preview" name="btn_preview" type="submit">
                                    <i class="fa fa-eye" aria-hidden="true"></i>
                                    {{ 'btn_preview'|trans({}, 'SonataAdminBundle') }}
                                </button>
                            {% endif %}
                            {# NEXT_MAJOR: remove default filter #}
                            {% if objectId|default(admin.id(object)) is not null %}
                                <button type="submit" class="btn btn-success" name="btn_update_and_edit"><i class="fa fa-save" aria-hidden="true"></i> {{ 'btn_update_and_edit_again'|trans({}, 'SonataAdminBundle') }}</button>

                                {% if admin.hasRoute('list') and admin.hasAccess('list') %}
                                    <button type="submit" class="btn btn-success" name="btn_update_and_list"><i class="fa fa-save"></i> <i class="fa fa-list" aria-hidden="true"></i> {{ 'btn_update_and_return_to_list'|trans({}, 'SonataAdminBundle') }}</button>
                                {% endif %}
                                {% if admin.hasRoute('prepare') and admin.hasAccess('prepare') %}
                                    <button type="submit" class="btn btn-success" name="btn_update_and_prepare"><i class="fa fa-share-square" aria-hidden="true"></i> {{ 'hg_email.label.update_and_prepare'|trans }}</button>
                                {% endif %}

                                {% if admin.hasRoute('delete') and admin.hasAccess('delete', object) %}
                                    {{ 'delete_or'|trans({}, 'SonataAdminBundle') }}
                                    <a class="btn btn-danger" href="{{ admin.generateObjectUrl('delete', object) }}"><i class="fa fa-minus-circle" aria-hidden="true"></i> {{ 'link_delete'|trans({}, 'SonataAdminBundle') }}</a>
                                {% endif %}

                                {% if admin.isAclEnabled() and admin.hasRoute('acl') and admin.hasAccess('acl', object) %}
                                    <a class="btn btn-info" href="{{ admin.generateObjectUrl('acl', object) }}"><i class="fa fa-users" aria-hidden="true"></i> {{ 'link_edit_acl'|trans({}, 'SonataAdminBundle') }}</a>
                                {% endif %}
                            {% else %}
                                {% if admin.hasroute('edit') and admin.hasAccess('edit') %}
                                    <button class="btn btn-success" type="submit" name="btn_create_and_edit"><i class="fa fa-save" aria-hidden="true"></i> {{ 'btn_create_and_edit_again'|trans({}, 'SonataAdminBundle') }}</button>
                                {% endif %}
                                {% if admin.hasRoute('prepare') and admin.hasAccess('prepare') %}
                                    <button type="submit" class="btn btn-success" name="btn_update_and_prepare"><i class="fa fa-share-square" aria-hidden="true"></i> {{ 'hg_email.label.create_and_prepare'|trans }}</button>
                                {% endif %}
                                {% if admin.hasroute('list') and admin.hasAccess('list') %}
                                    <button type="submit" class="btn btn-success" name="btn_create_and_list"><i class="fa fa-save"></i> <i class="fa fa-list" aria-hidden="true"></i> {{ 'btn_create_and_return_to_list'|trans({}, 'SonataAdminBundle') }}</button>
                                {% endif %}
                                <button class="btn btn-success" type="submit" name="btn_create_and_create"><i class="fa fa-plus-circle" aria-hidden="true"></i> {{ 'btn_create_and_create_a_new_one'|trans({}, 'SonataAdminBundle') }}</button>
                            {% endif %}
                        {% endif %}
                    {% endblock %}
                </div>
            {% endblock formactions %}
        </form>
    {% endif%}

    {{ sonata_block_render_event('sonata.admin.edit.form.bottom', { 'admin': admin, 'object': object }) }}


{% endblock %}
{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" href="{{ asset('bundles/hgabkaemail/css/template_edit.css') }}">
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script>
        function renderUsableVars()
        {
            $.post($('#usable-vars').data('url'), {data: $('form').serialize(), name:'{{ form.vars.name }}'}, function (data) {
              $('#usable-vars').html(data);
            });
        }
        $(function() {
            renderUsableVars();
        });
    </script>
{% endblock %}

src/Resources/views/Admin/Message/list_copy.html.twig
{% if admin.hasAccess('create')  %}
    <a href="{{ admin.generateObjectUrl('copy', object) }}"  class="btn btn-sm btn-default" title="{{ 'hg_email.label.copy'|trans }}">
        <i class="fa fa-copy" aria-hidden="true"></i>
        {{ 'hg_email.label.copy'|trans }}
    </a>
{% endif %}

src/Resources/views/Admin/Message/list_edit.html.twig
{% if object.prepareable %}
    {% include '@SonataAdmin/CRUD/list__action_edit.html.twig' %}
{% endif %}

src/Resources/views/Admin/Message/list_prepare.html.twig
{% if admin.hasAccess('prepare') and object.prepareable  %}
    <a href="{{ admin.generateObjectUrl('prepare', object) }}"  class="btn btn-sm btn-default" title="{{ 'hg_email.label.prepare'|trans }}">
        <i class="fa fa-share-square" aria-hidden="true"></i>
        {{ 'hg_email.label.prepare'|trans }}
    </a>
{% endif %}

src/Resources/views/Admin/Message/list_status.html.twig
{% extends '@SonataAdmin/CRUD/base_list_field.html.twig' %}
{% block field %}
{{ ('hg_email.statuses.' ~ value) | trans }}<br />
{% if object.beingSent %}
    {{ 'hg_email.statuses.send_data' | trans({'%recipient%' : object.sentMail, '%success%' : object.sentSuccess, '%fail%' : object.sentFail}) }}
{% endif %}
{% if object.prepared %}
    {{ ' (' ~ ('hg_email.statuses.send_date' | trans({'%date%' : ( object.sendAt is not empty ? (object.sendAt | format_datetime('long', 'short')) : ('hg_email.statuses.immidiately' | trans ))})) ~ ')' }}
{% endif %}
{% endblock %}

src/Resources/views/Admin/Message/list_testmail.html.twig
{% if admin.hasAccess('list')  %}
    <a href="{{ admin.generateObjectUrl('testmail', object) }}"  class="btn btn-sm btn-default" title="{{ 'hg_email.label.testmail'|trans }}">
        <i class="fa fa-envelope" aria-hidden="true"></i>
        {{ 'hg_email.label.testmail'|trans({'%message%': object.name}) }}
    </a>
{% endif %}

src/Resources/views/Admin/Message/list_unprepare.html.twig
{% if admin.hasAccess('prepare') and object.unprepareable  %}
    <a href="{{ admin.generateObjectUrl('unprepare', object) }}"  class="btn btn-sm btn-default" title="{{ 'hg_email.label.unprepare'|trans }}">
        <i class="fa fa-undo" aria-hidden="true"></i>
        {{ 'hg_email.label.unprepare'|trans }}
    </a>
{% endif %}

src/Resources/views/Admin/Message/list_webversion.html.twig
{% if admin.hasAccess('edit')  %}
    <a href="{{ admin.generateObjectUrl('webversion', object) }}" target="_blank" class="btn btn-sm btn-default" title="{{ 'hg_email.label.webversion'|trans }}">
        <i class="fa fa-globe" aria-hidden="true"></i>
        {{ 'hg_email.label.webversion'|trans }}
    </a>
{% endif %}

src/Resources/views/Admin/Message/prepare.html.twig
{% extends '@SonataAdmin/CRUD/base_edit.html.twig' %}
{% block title %}
    {{ "hg_email.title.prepare"|trans }}
{% endblock %}
{% block breadcrumb %}
    <div class="hidden-xs">
        <ol class="nav navbar-top-links breadcrumb">
            <li>
                <a href="{{ path('sonata_admin_dashboard') }}">{{ 'link_breadcrumb_dashboard' | trans({}, 'SonataAdminBundle') | raw }}</a>
            </li>
            {% if block('breadcrumb_between') is defined %}
                {{ block('breadcrumb_between') }}
            {% endif %}
            <li class="active"><span>{{ block('title') }}</span></li>
        </ol>
    </div>
{% endblock %}

{% block navbar_title %}
    {{- block('title') -}}
{% endblock %}

{% block form %}
    <form role="form" action="{{ admin.generateObjectUrl('prepare', object) }}" method="POST">

        {{ include('@SonataAdmin/Helper/render_form_dismissable_errors.html.twig') }}
        <div class="row">
            <div class="col-md-12">
                <div class="box box-primary">
                    <div class="box-header">
                        <h4 class="box-title">{{ 'hg_email.title.prepare'|trans }}</h4>
                    </div>
                    <div class="box-body">
                        <div class="sonata-ba-collapsed-fields">
                            {{ form_widget(form) }}
                        </div>
                    </div>
                </div>
            </div>
            <div class="sonata-ba-form-actions well well-small form-actions">
                <button type="submit" class="btn btn-success">
                    <i class="fa fa-share-square" aria-hidden="true"></i>
                    {{ 'hg_email.label.prepare'|trans }}
                </button>
                <a class="btn btn-danger" href="{{ admin.generateUrl('list') }}">
                    <i class="fa fa-ban" aria-hidden="true"></i>
                    {{ 'kuma_admin.form.cancel'|trans }}
                </a>
            </div>
            {{ form_rest(form) }}
        </div>
    </form>
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script src="{{ asset('/bundles/hgabkaemail/js/message_send.js') }}"></script>
{% endblock %}

src/Resources/views/Admin/Message/render_usable_vars.html.twig
{{ render_message_usable_vars(message) }}

src/Resources/views/Admin/Message/subscriber_recipient_form.html.twig
{% extends '@HgabkaEmail/Admin/recipient_type_form.html.twig' %}
{% block recipient_form %}
    {{ parent() }}
{% endblock %}
{% block javascripts %}
    <script>
        $(function(){
            $('#{{ child.addUnsubscribe.vars.id }}').on('change', function () {
                if ($(this).is(':checked')) {
                    $(this).closest('.panel-body').find('.unsub-link-text').closest('.form-group').show();
                } else {
                    $(this).closest('.panel-body').find('.unsub-link-text').val('');
                    $(this).closest('.panel-body').find('.unsub-link-text').closest('.form-group').hide();
                }
            });
        });
    </script>
{% endblock %}

src/Resources/views/Admin/Message/testmail.html.twig
{% extends '@SonataAdmin/CRUD/base_edit.html.twig' %}
{% block title %}
    {{ "hg_email.title.testmail"|trans({ '%message%': object.name}) }}
{% endblock %}
{% block breadcrumb %}
    <div class="hidden-xs">
        <ol class="nav navbar-top-links breadcrumb">
            <li>
                <a href="{{ path('sonata_admin_dashboard') }}">{{ 'link_breadcrumb_dashboard' | trans({}, 'SonataAdminBundle') | raw }}</a>
            </li>
            {% if block('breadcrumb_between') is defined %}
                {{ block('breadcrumb_between') }}
            {% endif %}
            <li class="active"><span>{{ block('title') }}</span></li>
        </ol>
    </div>
{% endblock %}

{% block navbar_title %}
    {{- block('title') -}}
{% endblock %}

{% block form %}
    <form role="form" action="{{ admin.generateObjectUrl('testmail', object) }}" method="POST">

        {{ include('@SonataAdmin/Helper/render_form_dismissable_errors.html.twig') }}
        <div class="row">
            <div class="col-md-12">
                <div class="box box-primary">
                    <div class="box-header">
                        <h4 class="box-title">{{ 'hg_email.title.testmail_general'|trans }}</h4>
                    </div>
                    <div class="box-body">
                        <div class="sonata-ba-collapsed-fields">
                            {{ form_widget(form) }}
                        </div>
                    </div>
                </div>
            </div>
            <div class="sonata-ba-form-actions well well-small form-actions">
                <button type="submit" class="btn btn-success">
                    <i class="fa fa-share-square" aria-hidden="true"></i>
                    {{ 'hg_email.label.send'|trans }}
                </button>
                <a class="btn btn-danger" href="{{ admin.generateUrl('list') }}">
                    <i class="fa fa-ban" aria-hidden="true"></i>
                    {{ 'kuma_admin.form.cancel'|trans }}
                </a>
            </div>
            {{ form_rest(form) }}
        </div>
    </form>
{% endblock %}