src/Entity/Message.php
<?php

namespace Hgabka\EmailBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Hgabka\Doctrine\Translatable\Annotation as Hgabka;
use Hgabka\Doctrine\Translatable\TranslatableInterface;
use Hgabka\EmailBundle\Enum\MessageStatusEnum;
use Hgabka\EmailBundle\Repository\MessageRepository;
use Hgabka\UtilsBundle\Entity\TranslatableTrait;
use Hgabka\UtilsBundle\Traits\TimestampableEntity;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Table(name: 'hg_email_message')]
#[ORM\Entity(repositoryClass: MessageRepository::class)]
class Message implements TranslatableInterface
{
    use TimestampableEntity;
    use TranslatableTrait;

    #[ORM\Id]
    #[ORM\GeneratedValue(strategy: 'AUTO')]
    #[ORM\Column(type: 'integer')]
    protected ?int $id = null;

    /**
     * @Hgabka\Translations(targetEntity="Hgabka\EmailBundle\Entity\MessageTranslation")
     */
    #[Hgabka\Translations(targetEntity: MessageTranslation::class)]
    protected Collection|array|null $translations = null;

    #[ORM\OneToMany(targetEntity: MessageSendList::class, cascade: ['all'], mappedBy: 'message', orphanRemoval: true)]
    #[Assert\Valid]
    protected Collection|array|null $sendLists = null;

    #[ORM\Column(name: 'to_data', type: 'json', nullable: true)]
    protected ?array $toData = null;

    #[ORM\Column(name: 'cc_data', type: 'json', nullable: true)]
    protected ?array $ccData = null;

    #[ORM\Column(name: 'bcc_data', type: 'json', nullable: true)]
    protected ?array $bccData = null;

    #[ORM\Column(name: 'send_at', type: 'datetime', nullable: true)]
    protected ?\DateTime $sendAt = null;

    #[ORM\Column(name: 'sent_at', type: 'datetime', nullable: true)]
    protected ?\DateTime $sentAt = null;

    #[ORM\Column(name: 'status', type: 'string', length: 20)]
    protected ?string $status = MessageStatusEnum::STATUS_INIT;

    #[ORM\ManyToOne(targetEntity: EmailLayout::class, inversedBy: 'messages', cascade: ['persist'])]
    #[ORM\JoinColumn(name: 'email_layout_id', referencedColumnName: 'id', onDelete: 'SET NULL')]
    protected ?EmailLayout $layout = null;

    #[ORM\Column(name: 'sent_mail', type: 'integer')]
    protected ?int $sentMail = 0;

    #[ORM\Column(name: 'sent_success', type: 'integer')]
    protected ?int $sentSuccess = 0;

    #[ORM\Column(name: 'sent_fail', type: 'integer')]
    protected ?int $sentFail = 0;

    #[ORM\Column(name: 'is_simple', type: 'boolean')]
    protected ?bool $isSimple = false;

    #[ORM\Column(name: 'locale', type: 'string', length: 2, nullable: true)]
    protected ?string $locale = null;

    /**
     * constructor.
     */
    public function __construct()
    {
        $this->translations = new ArrayCollection();
        $this->sendLists = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function setId(?int $id)
    {
        $this->id = $id;

        return $this;
    }

    public function getLayout(): ?EmailLayout
    {
        return $this->layout;
    }

    public function setLayout(?EmailLayout $layout): self
    {
        $this->layout = $layout;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setType(?string $status)
    {
        if (!\in_array($status, MessageStatusEnum::getAvailableStatuses(), true)) {
            throw new \InvalidArgumentException('Invalid type');
        }

        $this->status = $status;

        return $this;
    }

    public function getSendAt(): ?\DateTime
    {
        return $this->sendAt;
    }

    public function setSendAt(?\DateTime $sendAt = null): self
    {
        $this->sendAt = $sendAt;

        return $this;
    }

    public function getSentMail(): ?int
    {
        return $this->sentMail;
    }

    public function setSentMail(?int $sentMail): self
    {
        $this->sentMail = $sentMail;

        return $this;
    }

    public function getSentSuccess(): ?int
    {
        return $this->sentSuccess;
    }

    public function setSentSuccess(?int $sentSuccess): self
    {
        $this->sentSuccess = $sentSuccess;

        return $this;
    }

    public function getSentFail(): ?int
    {
        return $this->sentFail;
    }

    public function setSentFail(?int $sentFail): self
    {
        $this->sentFail = $sentFail;

        return $this;
    }

    public function getisSimple(): ?bool
    {
        return $this->isSimple;
    }

    public function setIsSimple(?bool $isSimple): self
    {
        $this->isSimple = $isSimple;

        return $this;
    }

    public function getLocale(): ?string
    {
        return $this->locale;
    }

    public function setLocale(?string $locale): self
    {
        $this->locale = $locale;

        return $this;
    }

    public function getSendLists(): Collection|array|null
    {
        return $this->sendLists;
    }

    public function setSendLists(Collection|array|null $sendLists): self
    {
        $this->sendLists = $sendLists;

        return $this;
    }

    public function addSendList(MessageSendList $sendList): self
    {
        if (!$this->sendLists->contains($sendList)) {
            $this->sendLists[] = $sendList;

            $sendList->setMessage($this);
        }

        return $this;
    }

    public function removeSendList(MessageSendList $sendList): self
    {
        $this->sendLists->removeElement($sendList);

        return $this;
    }

    public static function getTranslationEntityClass(): string
    {
        return MessageTranslation::class;
    }

    public function getToData(): ?array
    {
        return $this->toData;
    }

    public function setToData(?array $toData): self
    {
        $this->toData = $toData;

        return $this;
    }

    public function getCcData(): ?array
    {
        return $this->ccData;
    }

    public function setCcData(?array $ccData): self
    {
        $this->ccData = $ccData;

        return $this;
    }

    public function getBccData(): ?array
    {
        return $this->bccData;
    }

    public function setBccData(?array $bccData)
    {
        $this->bccData = $bccData;

        return $this;
    }

    public function getSentAt(): ?\DateTime
    {
        return $this->sentAt;
    }

    public function setSentAt(?\DateTime $sentAt): self
    {
        $this->sentAt = $sentAt;

        return $this;
    }

    public function isPrepareable(): bool
    {
        return MessageStatusEnum::STATUS_INIT === $this->getStatus() || null === $this->getId();
    }

    public function isUnprepareable(): bool
    {
        return \in_array($this->getStatus(), [MessageStatusEnum::STATUS_KULDENDO, MessageStatusEnum::STATUS_FOLYAMATBAN], true);
    }

    public function isBeingSent(): bool
    {
        return \in_array($this->getStatus(), [MessageStatusEnum::STATUS_ELKULDVE, MessageStatusEnum::STATUS_FOLYAMATBAN], true);
    }

    public function isPrepared(): bool
    {
        return MessageStatusEnum::STATUS_KULDENDO === $this->getStatus();
    }

    public function getSendTime(): array
    {
        if (null === $this->sendAt) {
            return [
                'type' => 'now',
                'time' => null,
            ];
        }

        return [
                'type' => 'later',
                'time' => $this->sendAt,
            ];
    }

    public function setSendTime(?array $data): self
    {
        if (!isset($data['type']) || 'now' === $data['type']) {
            $this->setSendAt(null);
        } else {
            $this->setSendAt($data['time']);
        }

        return $this;
    }

    public function getSubject(?string $locale = null): ?string
    {
        return $this->translate($locale)->getSubject();
    }

    public function setStatus(?string $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getStatusDisplay(): string
    {
        $choices = MessageStatusEnum::getStatusTextChoices();

        return $choices[$this->getStatus()] ?? '';
    }

    public function getName(?string $locale = null): ?string
    {
        return $this->translate($locale)->getName();
    }

    public function getFromName(?string $locale = null): ?string
    {
        return $this->translate($locale)->getFromName();
    }

    public function getFromEmail(?string $locale = null): ?string
    {
        return $this->translate($locale)->getFromEmail();
    }
}

src/Controller/MessageController.php
<?php

namespace Hgabka\EmailBundle\Controller;

use Doctrine\Persistence\ManagerRegistry;
use Hgabka\EmailBundle\Entity\MessageList;
use Hgabka\EmailBundle\Entity\MessageListSubscription;
use Hgabka\EmailBundle\Entity\MessageQueue;
use Hgabka\EmailBundle\Entity\MessageSubscriber;
use Hgabka\EmailBundle\Helper\MailBuilder;
use Hgabka\EmailBundle\Helper\RecipientManager;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Mime\Address;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\Routing\RouterInterface;

class MessageController extends AbstractController
{
    /**
     * The webversion action.
     *
     * @param mixed $id
     * @param mixed $hash
     *
     * @return Response
     */
    #[Route('/{id}/webversion/{hash}', name: 'hgabka_email_message_webversion', requirements: ['id' => '\d+'], methods: ['GET'])]
    public function webversionAction(Request $request, RouterInterface $router, MailBuilder $mailBuilder, RecipientManager $recipientManager, ManagerRegistry $doctrine, int $id, string $hash): Response
    {
        /** @var MessageQueue $queue */
        $queue = $doctrine->getRepository(MessageQueue::class)->find($id);
        if (!$queue || $queue->getHash() !== $hash) {
            throw $this->createNotFoundException('Invalid message');
        }
        $toName = $queue->getToName();
        $toEmail = $queue->getToEmail();

        $to = empty($toName) ? new Address($toEmail) : new Address($toEmail, $toName);
        $params = json_decode($queue->getParameters(), true);

        if (!isset($params['type'])) {
            return false;
        }
        $recType = $recipientManager->getMessageRecipientType($params['type']);
        if (!$recType) {
            return false;
        }
        $recType->setParams($params['typeParams'] ?? []);
        if (!isset($params['vars'])) {
            $params['vars'] = [];
        }

        ['bodyHtml' => $bodyHtml] = $mailBuilder->createMessageMail($queue->getMessage(), $to, $queue->getLocale(), true, $params, $recType, false, true, $queue);

        return new Response($bodyHtml);
    }

    /**
     * The unsubscribe action.
     *
     * @param mixed $token
     *
     * @return Response
     */
    #[Route('/unsubscribe/{token}', name: 'hgabka_email_message_unsubscribe')]
    public function unsubscribeAction(Request $request, ManagerRegistry $doctrine, string $token): Response
    {
        $em = $doctrine->getManager();

        $subscr = $em
            ->getRepository(MessageSubscriber::class)
            ->findOneByToken($token)
        ;

        if (!$subscr) {
            throw $this->createNotFoundException('Missing subscriber');
        }

        if ($request->query->has('list_id')) {
            $list = $em
                ->getRepository(MessageList::class)
                ->findOneById($request->query->get('list_id'))
            ;

            if ($list) {
                $sub = $em
                    ->getRepository(MessageListSubscription::class)
                    ->findForSubscriberAndList($subscr, $list)
                ;

                if ($sub) {
                    $em->remove($sub);
                    $em->flush();
                }
            }
        } else {
            $em->remove($subscr);
            $em->flush();
        }

        return $this->render('@HgabkaEmail/Message/unsubscribe.html.twig');
    }
}

src/Resources/views/AdminList/Message/_send_item_action.html.twig
{% if isNew or entity.isPrepareable() %}
    <button name="save_and_send" type="submit" class="btn btn-secondary btn--raise-on-hover">
        {{ itemAction.getLabelFor(isNew ? null : entity) | trans }}
    </button>
{% endif %}

src/Resources/views/AdminList/Message/_send_item_list_action.html.twig
{% if item.isPrepareable() %}
    {% set url = itemAction.getUrlFor(item) %}
    {% if url %}
        <a href="{{ path(url["path"], url[("params")]) }}" class="link--text table__actions__item" title="{{ itemAction.getLabelFor(item) | trans }}">
            {% if itemAction.getIconFor(item) is not null %}
                <i class="fa fa-{{ itemAction.getIconFor(item) }}"></i>
            {% endif %}
        </a>
    {% endif %}
{% endif %}

src/Resources/views/AdminList/Message/_status.html.twig
{{ ('hgabka_kuma_email.statuses.' ~ object) | trans }}<br />
{% if row.isBeingSent() %}
    {{ 'hgabka_kuma_email.statuses.send_data' | trans({'%recipient%' : row.sentMail, '%success%' : row.sentSuccess, '%fail%' : row.sentFail}) }}
{% endif %}
{% if row.isPrepared() %}
    {{ ' (' ~ ('hgabka_kuma_email.statuses.send_date' | trans({'%date%' : ( row.sendAt is not empty ? (row.sendAt() | format_datetime('long', 'short')) : ('hgabka_kuma_email.statuses.immidiately' | trans ))})) ~ ')' }}
{% endif %}

src/Resources/views/AdminList/Message/_unprepare_item_list_action.html.twig
{% if item.isUnprepareable() %}
    {% set url = itemAction.getUrlFor(item) %}
    {% if url %}
        <a href="{{ path(url["path"], url[("params")]) }}" class="link--text table__actions__item" title="{{ itemAction.getLabelFor(item) | trans }}">
            {% if itemAction.getIconFor(item) is not null %}
                <i class="fa fa-{{ itemAction.getIconFor(item) }}"></i>
            {% endif %}
        </a>
    {% endif %}
{% endif %}

src/Resources/views/AdminList/Message/_usable_vars.html.twig
{% set vars = mail_builder.getMessageVars() %}
{% if vars is not empty %}
    <div class="form-header-block">
        <h4>{{ 'hgabka_kuma_email.labels.usable_vars' | trans }}</h4>
        <ul style="list-style-type: none">
            {% for var, explanation in vars %}
                <li><span style="display:inline-block;width:150px">{{ var }}</span>:  {{ explanation | trans }}</li>
            {% endfor %}
        </ul>
    </div>
{% endif %}

src/Resources/views/AdminList/Message/_web_item_list_action.html.twig
{% set url = itemAction.getUrlFor(item) %}
{% if url %}
    <a target="_blank" href="{{ path(url["path"], url[("params")]) }}" class="link--text table__actions__item" title="{{ itemAction.getLabelFor(item) | trans }}">
        {% if itemAction.getIconFor(item) is not null %}
            <i class="fa fa-{{ itemAction.getIconFor(item) }}"></i>
        {% endif %}
    </a>
{% endif %}

src/Resources/views/AdminList/Message/edit.html.twig
{% extends 'KunstmaanAdminListBundle:Default:add_or_edit.html.twig' %}

{% block content %}
    {% include 'HgabkaKunstmaanEmailBundle:AdminList/Message:_usable_vars.html.twig' %}
    {{ parent() }}
{% endblock %}

src/Resources/views/AdminList/Message/send.html.twig
{% extends 'KunstmaanAdminListBundle:Default:add_or_edit.html.twig' %}
{% block admin_page_title %}
    <div class="col-sm-6 col-md-8">
        <h1 class="app__content__header__title">
                {{ 'hgabka_kuma_email.titles.message.send' | trans }}
        </h1>
    </div>
{% endblock %}

{% block actions %}
    <button type="submit" class="btn btn-primary btn--raise-on-hover">
        {{ 'hgabka_kuma_email.labels.send' | trans }}
    </button>
    <a href="{{ path(adminlistconfigurator.getIndexUrl()["path"], adminlistconfigurator.getIndexUrl()["params"]) }}" class="btn btn-default btn--raise-on-hover">
        {{ 'kuma_admin_list.form.cancel' | trans }}
    </a>
{% endblock %}

{% block form_content %}
    {{ form_row(form.sendTime.type) }}
    {{ form_row(form.sendTime.time) }}
    {{ form_rest(form) }}
{% endblock %}

{% block extrajavascript %}
    {{ parent() }}
    <script src="{{ asset('/bundles/hgabkakunstmaanemail/js/message_send.js') }}"></script>
{% endblock %}

src/Resources/views/AdminList/Message/testmail.html.twig
{% extends 'KunstmaanAdminListBundle:Default:add_or_edit.html.twig' %}
{% block admin_page_title %}
    <div class="col-sm-6 col-md-8">
        <h1 class="app__content__header__title">
            {{ 'hgabka_kuma_email.titles.message.testmail' | trans }}
        </h1>
    </div>
{% endblock %}

{% block actions %}
    <button type="submit" class="btn btn-primary btn--raise-on-hover">
        {{ 'hgabka_kuma_email.labels.send' | trans }}
    </button>
    <a href="{{ path(adminlistconfigurator.getIndexUrl()["path"], adminlistconfigurator.getIndexUrl()["params"]) }}" class="btn btn-default btn--raise-on-hover">
        {{ 'kuma_admin_list.form.cancel' | trans }}
    </a>
{% endblock %}

{% block form_content %}
    {{ form_rest(form) }}
{% endblock %}